
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Sat Aug 27 16:28:09 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  
  public static final int PROGRAM       = 0;
  public static final int CLASS_DECL    = 1;
  public static final int FIELD_DECL    = 2;
  public static final int METHOD_DECL   = 3;
  public static final int BODY		    = 4;
  public static final int BLOCK		    = 5;
  public static final int TYPE		    = 6;
  public static final int STATEMENT     = 7;
  public static final int ASSIGN_OP     = 8;
  public static final int METHOD_CALL   = 9;
  public static final int LOCATION 	    = 10;
  public static final int EXPR		    = 11;
  public static final int BIN_OP	    = 12;
  public static final int ARITH_OP	    = 13;
  public static final int REL_OP	    = 14;
  public static final int EQ_OP         = 15;
  public static final int COND_OP       = 16;
  public static final int LITERAL	    = 17;
  public static final int ID  	 	    = 18;
  public static final int ALPHA_NUM     = 19;
  public static final int ALPHA 	    = 20;
  public static final int DIGIT		    = 21;
  public static final int INT_LITERAL   = 22;
  public static final int BOOL_LITERAL  = 23;
  public static final int FLOAT_LITERAL = 24;
  public static final int ERROR 		= 25;
  public static final int EOF 			= 26;
  

  
}

