
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140611 (SVN rev 31)
// Fri Sep 02 20:24:08 ART 2016
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CONT = 8;
  public static final int PLUSPLUS = 28;
  public static final int LBRACKET = 42;
  public static final int BOOL_TYPE = 2;
  public static final int RET = 14;
  public static final int SMALLER = 31;
  public static final int LPAREN = 38;
  public static final int SEMI = 19;
  public static final int FOR = 12;
  public static final int MINUS = 23;
  public static final int REALNUMBER = 45;
  public static final int RPAREN = 39;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int COMMA = 21;
  public static final int DIV = 25;
  public static final int EXTERN = 10;
  public static final int VOID_TYPE = 5;
  public static final int PLUS = 22;
  public static final int ASSIGN = 16;
  public static final int IF = 13;
  public static final int ID = 46;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 27;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 29;
  public static final int error = 1;
  public static final int DISTINCT = 30;
  public static final int MOD = 26;
  public static final int INT_TYPE = 4;
  public static final int BREAK = 6;
  public static final int BIGGER = 32;
  public static final int DOC = 20;
  public static final int TIMES = 24;
  public static final int CLASS_DECL = 7;
  public static final int LBRACE = 40;
  public static final int ELSE = 9;
  public static final int ASSIGNP = 17;
  public static final int WHILE = 15;
  public static final int ASSIGNM = 18;
  public static final int RBRACE = 41;
  public static final int GTOE = 34;
  public static final int FLOAT_TYPE = 3;
  public static final int LTOE = 33;
  public static final int BOOL_LITERAL = 11;
  public static final int INTNUMBER = 44;
}

